mh4_editor_homepage:
    path:    /
    defaults: { _controller: MH4EditorBundle:Home:index }

mh4_login_frontend:
    path:    /login
    defaults: { _controller: MH4EditorBundle:Login:login }

mh4_login_check:
    path:    /login/check
    defaults: { _controller: MH4EditorBundle:Login:checkLogin }

m4h_register_frontend:
    path:    /register
    defaults: { _controller: MH4EditorBundle:Register:showForm }

m4h_register_backend:
    path:    /register/done
    defaults: { _controller: MH4EditorBundle:Register:register }

mh4_item_list:
    path:   /item/list
    defaults: { _controller: MH4EditorBundle:Item:list }

mh4_item_edit:
    path:   /item/edit/{item_id}
    defaults: { _controller: MH4EditorBundle:Item:edit }