mh4_editor_cron:
    path:    /admin/cron/add
    defaults: { _controller: MH4EditorBundle:CronTask:cron }

mh4_editor_homepage:
    path:    /
    defaults: { _controller: MH4EditorBundle:Home:index }

mh4_editor_changelang:
    path:    /changelang/{lang}
    defaults: { _controller: MH4EditorBundle:Home:changeLanguageByUrl }

mh4_login_frontend:
    path:    /login
    defaults: { _controller: MH4EditorBundle:Login:login }

mh4_logout_frontend:
    path:   /logout

mh4_login_check:
    path:    /login/check
    defaults: { _controller: MH4EditorBundle:Login:checkLogin }

m4h_register_frontend:
    path:    /register
    defaults: { _controller: MH4EditorBundle:Register:showForm }

m4h_register_backend:
    path:    /register/done
    defaults: { _controller: MH4EditorBundle:Register:register }

mh4_item_list:
    path:   /item/list
    defaults: { _controller: MH4EditorBundle:Item:list }

mh4_item_topbuyedlist:
    path:   /admin/item/topbuyedlist
    defaults: { _controller: MH4EditorBundle:Home:showTopListItem }

mh4_item_boughtlist:
    path:   /admin/item/user/boughtlist
    defaults: { _controller: MH4EditorBundle:Home:showBoughtUserList }

mh4_item_edit:
    path:   /item/edit/{item_id}
    defaults: { _controller: MH4EditorBundle:Item:edit }

mh4_item_buy:
    path:   /item/buy/{item_name}
    defaults: { _controller: MH4EditorBundle:Item:buy }
    requirements: { item_name: "([a-f0-9\wáéíóúÁÉÍÓÚ\.\+]+)( |[a-f0-9\d\wáéíóúÁÉÍÓÚ\.\+]+|')*" }
    methods: [PUT]

mh4_item_sell:
    path:   /item/sell/{item_id}
    defaults: { _controller: MH4EditorBundle:Item:sell }

mh4_file_upload:
    path:   /user/savefile/upload
    defaults: { _controller: MH4EditorBundle:User:fileUpload }

mh4_file_download:
    path:   /user/savefile/download
    defaults: { _controller: MH4EditorBundle:User:fileDownload }

mh4_user_accesslist:
    path:   /admin/user/accesslist
    defaults: { _controller: MH4EditorBundle:Home:showUserAccessList }

mh4_talisman_creator:
    path:   /talismancreator
    defaults: { _controller: MH4EditorBundle:Home:showTalismanCreator}

mh4_talisman_generatedlist:
    path:   /admin/talisman/generated
    defaults: { _controller: MH4EditorBundle:Home:showTalismanGenerated}

mh4_talisman_list:
    path:   /talismancreator/list
    defaults: { _controller: MH4EditorBundle:Talisman:list}

mh4_talisman_ability_list:
    path:   /talismancreator/abilitylist
    defaults: { _controller: MH4EditorBundle:Talisman:abilityList}

mh4_gen_talisman:
    path:   /talismancreator/gentalisman
    defaults: { _controller: MH4EditorBundle:Talisman:genTalisman}

mh4_char_custom:
    path: /character/custom
    defaults: { _controller: MH4EditorBundle:Home:showCharacterCustom}

mh4_char_custom_save:
    path: /character/custom/save
    defaults: { _controller: MH4EditorBundle:User:saveCharacterInfo}

mh4_debug:
    path:    /debug
    defaults: { _controller: MH4EditorBundle:Home:debug}

mh4_confirm_token:
    path:   /user/confirm/token/{token}
    defaults: { _controller: MH4EditorBundle:User:confirmToken}