mh4_editor_homepage:
    path:    /
    defaults: { _controller: MH4EditorBundle:Home:index }

mh4_login_frontend:
    path:    /login
    defaults: { _controller: MH4EditorBundle:Login:login }

m4h_register_frontend:
    path:    /register
    defaults: { _controller: MH4EditorBundle:Register:showForm }

m4h_register_backend:
    path:    /register/done
    defaults: { _controller: MH4EditorBundle:Register:register }