mh4_editor_homepage:
    path:    /
    defaults: { _controller: MH4EditorBundle:Home:index }

mh4_login_frontend:
    path:    /login
    defaults: { _controller: MH4EditorBundle:Login:login }

mh4_login_check:
    path:    /login/check
    defaults: { _controller: MH4EditorBundle:Login:checkLogin }

m4h_register_frontend:
    path:    /register
    defaults: { _controller: MH4EditorBundle:Register:showForm }

m4h_register_backend:
    path:    /register/done
    defaults: { _controller: MH4EditorBundle:Register:register }

mh4_item_list:
    path:   /item/list
    defaults: { _controller: MH4EditorBundle:Item:list }

mh4_item_edit:
    path:   /item/edit/{item_id}
    defaults: { _controller: MH4EditorBundle:Item:edit }

mh4_item_buy:
    path:   /item/buy/{item_name}
    defaults: { _controller: MH4EditorBundle:Item:buy }
    requirements: { item_name: \w+\s+'*-*_* }

mh4_item_sell:
    path:   /item/sell/{item_id}
    defaults: { _controller: MH4EditorBundle:Item:sell }

mh4_file_upload:
    path:   /user/savefile/upload
    defaults: { _controller: MH4EditorBundle:User:fileUpload }

mh4_file_download:
    path:   /user/savefile/download
    defaults: { _controller: MH4EditorBundle:User:fileDownload }
