UPDATE abilities SET description_en = 'Doubles the Skill Points on torso equipment.' WHERE id=1;
UPDATE abilities SET description_en = 'Skills that increase Attack and raise Sharpness. (Blademaster Only)' WHERE id=2;
UPDATE abilities SET description_en = 'Skills that affect the power of multiple types of Bowgun ammo and Bow arrows. (Gunner Only)' WHERE id=3;
UPDATE abilities SET description_en = 'Skills that prevent Poison, Paralysis, Sleep, and Stun.' WHERE id=4;
UPDATE abilities SET description_en = 'Skills that reduce the likelihood of fainting, and greatly increase Attack and Defense when your Health falls below a certain level.' WHERE id=5;
UPDATE abilities SET description_en = 'Skills that increase Dung Bomb efficacy and lessen or negate special blights.' WHERE id=6;
UPDATE abilities SET description_en = 'Skills that augment evasive abilities.' WHERE id=7;
UPDATE abilities SET description_en = 'Skills that are particularly useful with cutting weapons. (Blademaster Only)' WHERE id=8;
UPDATE abilities SET description_en = 'Skills that increase Defense and negate the effects of Defense Down.' WHERE id=9;
UPDATE abilities SET description_en = 'Skills that deal more powerful attacks against enemy weak points.' WHERE id=10;
UPDATE abilities SET description_en = 'Skills that affect the speed at which L. Sword/D. Blades/S. Axe gauges, C. Blade phials, and Bow/G. Sword/ Hammer charge attacks are charged. Also adds benefits to eating meat.' WHERE id=11;
UPDATE abilities SET description_en = 'Skills that improve blocking ability and increase Stamina recovery speed.' WHERE id=12;
UPDATE abilities SET description_en = 'Skills that increase evade distance; also increase Attack when your Health Gauge is full.' WHERE id=13;
UPDATE abilities SET description_en = 'Skills that increase the power of elemental attacks and extend the effect time of certain items.' WHERE id=14;
UPDATE abilities SET description_en = 'Skills that increase your ability to gather items and mine Charms.' WHERE id=15;
UPDATE abilities SET description_en = 'Skills that increase Quest Rewards, and Reward Items for capturing monsters.' WHERE id=16;
UPDATE abilities SET description_en = 'Skills that release the latent elemental properties in some weapons that don\'t have elements.' WHERE id=17;
UPDATE abilities SET description_en = 'Skills that prevent your attacks from being deflected. (Blademaster Only)' WHERE id=18;
UPDATE abilities SET description_en = 'Skills that increase your weapon\'s Sharpness. (Blademaster Only)' WHERE id=19;
UPDATE abilities SET description_en = 'Skills that increase the likelihood that draw attacks will be critical. (Blademaster Only)' WHERE id=20;
UPDATE abilities SET description_en = 'Skills that grant the ability to Stun monsters with draw attacks from cutting weapons. (Blademaster Only)' WHERE id=21;
UPDATE abilities SET description_en = 'Skills that affect reloading speed. (Gunner Only)' WHERE id=22;
UPDATE abilities SET description_en = 'Skills that affect recoil when firing. (Bowgun Only)' WHERE id=23;
UPDATE abilities SET description_en = 'Skills that allow one extra shot to be fired while Rapid Firing a Light Bowgun. (Bowgun Only)' WHERE id=24;
UPDATE abilities SET description_en = 'Skills that empower you for a limited time when certain conditions are met.' WHERE id=25;
UPDATE abilities SET description_en = 'Skills that increase your abilities when a large monster becomes angry.' WHERE id=26;
UPDATE abilities SET description_en = 'Skills that lessen your reaction when attacked.' WHERE id=27;
UPDATE abilities SET description_en = 'Skills that increase your ability to mine Charms.' WHERE id=28;
UPDATE abilities SET description_en = 'Skills that increase damage when striking body parts upon which your attacks are highly effective.' WHERE id=29;
UPDATE abilities SET description_en = 'Skills that negate the effects of all elemental blights.' WHERE id=30;
UPDATE abilities SET description_en = 'Skills that affect Attack.' WHERE id=31;
UPDATE abilities SET description_en = 'Skills that affect Defense.' WHERE id=32;
UPDATE abilities SET description_en = 'Skills that affect the number of times you can gather or mine, except in special cases.' WHERE id=33;
UPDATE abilities SET description_en = 'Skills that make carving easier.' WHERE id=34;
UPDATE abilities SET description_en = 'Skills that affect Quest Rewards, except in special cases.' WHERE id=35;
UPDATE abilities SET description_en = 'Skills that affect the number of Reward Items obtained for capturing monsters.' WHERE id=36;
UPDATE abilities SET description_en = 'Skills that increase the power of Ballista, Cannon, and Gunlance ammo, plus Wyvern\'s Fire, Impact-type Charge Blade phials, and Crag shots (Crag S).' WHERE id=37;
UPDATE abilities SET description_en = 'Skills that affect the length of the invulnerability period when evading.' WHERE id=38;
UPDATE abilities SET description_en = 'Skills that affect the maximum size of your Health Gauge.' WHERE id=39;
UPDATE abilities SET description_en = 'Skills that negate the effects of large monsters\' roars.' WHERE id=40;
UPDATE abilities SET description_en = 'Skills that affect the rate at which your weapon loses Sharpness when you attack. (Blademaster Only)' WHERE id=41;
UPDATE abilities SET description_en = 'Skills that affect the likelihood of standing your ground when blocking an attack.' WHERE id=42;
UPDATE abilities SET description_en = 'Skills that cause previously unblockable attacks to become blockable.' WHERE id=43;
UPDATE abilities SET description_en = 'Skills that affect how fast you can sharpen your weapon. (Blademaster Only)' WHERE id=44;
UPDATE abilities SET description_en = 'Skills that affect whether Attack and Defense bonuses are granted when Health drops below a certain level.' WHERE id=45;
UPDATE abilities SET description_en = 'Skills that increase bomb damage and Combination success rate, and increase the power of Blast attacks.' WHERE id=46;
UPDATE abilities SET description_en = 'Skills that affect the strength of abnormal status attacks (Paralysis, Poison, Sleep).' WHERE id=47;
UPDATE abilities SET description_en = 'Skills that affect Stamina depletion for actions other than evasion and blocking.' WHERE id=48;
UPDATE abilities SET description_en = 'Skills that increase your ability to wound monster body parts.' WHERE id=49;
UPDATE abilities SET description_en = 'Skills that affect evade distance.' WHERE id=50;
UPDATE abilities SET description_en = 'Skills that increase weapon- sheathing speed.' WHERE id=51;
UPDATE abilities SET description_en = 'Skills that affect the speed at which Long Sword, Dual Blades, and Switch Axe gauges, Charge Blade phials, and Bow, Great Sword, and Hammer charge attacks are charged.' WHERE id=52;
UPDATE abilities SET description_en = 'Skills that increase certain attacks - ability to Exhaust monsters.' WHERE id=53;
UPDATE abilities SET description_en = 'Skills that increase Attack when your Health Gauge is full.' WHERE id=54;
UPDATE abilities SET description_en = 'Skills that allow you to barely withstand a lethal blow without fainting.' WHERE id=55;
UPDATE abilities SET description_en = 'Skills that increase the ammo capacity of Bowguns and Gunlances, the phial capacity of Charge Blades, and the charge attack capacity of Bows.' WHERE id=56;
UPDATE abilities SET description_en = 'Skills that increase the power of Normal shots (Normal S) and Rapid-type arrows. (Gunner Only)' WHERE id=57;
UPDATE abilities SET description_en = 'Skills that increase the power of Pierce shots (Pierce S) and Pierce-type arrows. (Gunner Only)' WHERE id=58;
UPDATE abilities SET description_en = 'Skills that increase the power of Pellet shots (Pellet S) and Spread-type arrows. (Gunner Only)' WHERE id=59;
UPDATE abilities SET description_en = 'Skills that affect the likelihood of Stunning monsters.' WHERE id=60;
UPDATE abilities SET description_en = 'Skills that negate the effects of lowered Defense.' WHERE id=61;
UPDATE abilities SET description_en = 'Skills that affect the effect time of certain items.' WHERE id=62;
UPDATE abilities SET description_en = 'Skills that allow Normal shots (Normal S) to be loaded. (Bowgun Only)' WHERE id=63;
UPDATE abilities SET description_en = 'Skills that allow Pierce shots (Pierce S) to be loaded. (Bowgun Only)' WHERE id=64;
UPDATE abilities SET description_en = 'Skills that allow Pellet shots (Pellet S) to be loaded. (Bowgun Only)' WHERE id=65;
UPDATE abilities SET description_en = 'Skills that allow Crag shots (Crag S) to be loaded. (Bowgun Only)' WHERE id=66;
UPDATE abilities SET description_en = 'Skills that allow Cluster shots (Clust S) to be loaded. (Bowgun Only)' WHERE id=67;
UPDATE abilities SET description_en = 'Skills that allow Slicing shots (Slicing S) to be loaded. (Bowgun Only)' WHERE id=68;
UPDATE abilities SET description_en = 'Skills that allow Blast shots (Blast S) to be loaded. (Bowgun Only)' WHERE id=69;
UPDATE abilities SET description_en = 'Skills that allow Poison coatings to be set. (Bow Only)' WHERE id=70;
UPDATE abilities SET description_en = 'Skills that allow Paralysis coatings to be set. (Bow Only)' WHERE id=71;
UPDATE abilities SET description_en = 'Skills that allow Sleep coatings to be set. (Bow Only)' WHERE id=72;
UPDATE abilities SET description_en = 'Skills that allow Power coatings to be set. (Bow Only)' WHERE id=73;
UPDATE abilities SET description_en = 'Skills that allow Close-range coatings to be set. (Bow Only)' WHERE id=74;
UPDATE abilities SET description_en = 'Skills that allow Exhaust coatings to be set. (Bow Only)' WHERE id=75;
UPDATE abilities SET description_en = 'Skills that allow Blast coatings to be set. (Bow Only)' WHERE id=76;
UPDATE abilities SET description_en = 'Skills that affect Deviation when firing. (Bowgun Only)' WHERE id=77;
UPDATE abilities SET description_en = 'Skills that affect the power of Fire attacks and Flaming shots (Flaming S).' WHERE id=78;
UPDATE abilities SET description_en = 'Skills that affect the power of Water attacks and Water shots (Water S).' WHERE id=79;
UPDATE abilities SET description_en = 'Skills that affect the power of Thunder attacks and Thunder shots (Thunder S).' WHERE id=80;
UPDATE abilities SET description_en = 'Skills that affect the power of Ice attacks and Freeze shots (Freeze S).' WHERE id=81;
UPDATE abilities SET description_en = 'Skills that affect the power of Dragon attacks and Dragon shots (Dragon S).' WHERE id=82;
UPDATE abilities SET description_en = 'Skills that affect the strength of elemental attacks (Fire, Water, Thunder, Ice, Dragon).' WHERE id=83;
UPDATE abilities SET description_en = 'Skills that affect Fire resistance.' WHERE id=84;
UPDATE abilities SET description_en = 'Skills that affect Water resistance.' WHERE id=85;
UPDATE abilities SET description_en = 'Skills that affect Thunder resistance.' WHERE id=86;
UPDATE abilities SET description_en = 'Skills that affect Ice resistance.' WHERE id=87;
UPDATE abilities SET description_en = 'Skills that affect Dragon resistance.' WHERE id=88;
UPDATE abilities SET description_en = 'Skills that increase the speed of carving, gathering, bug catching and mining.' WHERE id=89;
UPDATE abilities SET description_en = 'Skills that grant detailed information on large monsters displayed on the Map.' WHERE id=90;
UPDATE abilities SET description_en = 'Skills that allow you to know exactly when it becomes possible to capture marked monsters.' WHERE id=91;
UPDATE abilities SET description_en = 'Skills that affect the efficacy of Health recovery items.' WHERE id=92;
UPDATE abilities SET description_en = 'Skills that transfer the effects of certain items to companions in the same area.' WHERE id=93;
UPDATE abilities SET description_en = 'Skills that decrease the likelihood of Horn items breaking, and increase the effect time of Hunting Horn melodies.' WHERE id=94;
UPDATE abilities SET description_en = 'Skills that increase your Attack and Defense every time you fall in battle.' WHERE id=95;
UPDATE abilities SET description_en = 'Skills that allow consumption of Raw Meat, and increase the efficacy of meat items.' WHERE id=96;
UPDATE abilities SET description_en = 'Skills that affect the efficacy of items that increase your Stamina.' WHERE id=97;
UPDATE abilities SET description_en = 'Skills that affect Stamina depletion when evading, blocking, etc.' WHERE id=98;
UPDATE abilities SET description_en = 'Skills that affect Stamina recovery speed.' WHERE id=99;
UPDATE abilities SET description_en = 'Skills that negate or reduce the effect of large monsters - Wind Pressure.' WHERE id=100;
UPDATE abilities SET description_en = 'Skills that affect how fast you consume meat and other items.' WHERE id=101;
UPDATE abilities SET description_en = 'Skills that affect your Combination success rate.' WHERE id=102;
UPDATE abilities SET description_en = 'Skills that maximize the number of items created through a successful Combination.' WHERE id=103;
UPDATE abilities SET description_en = 'Skills that eliminate the need for a map and improve fishing and cooking performance during quests.' WHERE id=104;
UPDATE abilities SET description_en = 'Skills that affect the speed at which your health decreases in hot areas and the damage inflicted by lava.' WHERE id=105;
UPDATE abilities SET description_en = 'Skills that affect the speed at which your maximum Stamina depletes in cold areas.' WHERE id=106;
UPDATE abilities SET description_en = 'Skills that let you invigorate Palicoes that accompany you during Quests, and increase their abilities.' WHERE id=107;
UPDATE abilities SET description_en = 'Skills that increase the abilities of Palicoes that accompany you during Quests.' WHERE id=108;
UPDATE abilities SET description_en = 'Skills that let you invigorate Palicoes that accompany you during Quests.' WHERE id=109;
UPDATE abilities SET description_en = 'Skills that affect recovery speed from temporary damage (the red portion of the Health Gauge).' WHERE id=110;
UPDATE abilities SET description_en = 'Skills that affect how easily Pickaxes, Bug Nets, Boomerangs and Horns break.' WHERE id=111;
UPDATE abilities SET description_en = 'Skills that affect the amount of damage you take when attacked.' WHERE id=112;
UPDATE abilities SET description_en = 'Skills that affect the speed at which your maximum Stamina depletes.' WHERE id=113;
UPDATE abilities SET description_en = 'Skills that make transporting items such as eggs easier.' WHERE id=114;
UPDATE abilities SET description_en = 'Skills that increase bomb- and trap-setting speed as well as trap Combination success rate.' WHERE id=115;
UPDATE abilities SET description_en = 'Skills that increase your ability to gather Honey.' WHERE id=116;
UPDATE abilities SET description_en = 'Skills that negate or double the effects of enemy Poison attacks on you.' WHERE id=117;
UPDATE abilities SET description_en = 'Skills that negate or double the effects of enemy Paralysis attacks on you.' WHERE id=118;
UPDATE abilities SET description_en = 'Skills that negate or double the effects of enemy Sleep attacks on you.' WHERE id=119;
UPDATE abilities SET description_en = 'Skills that affect the likelihood of becoming Stunned.' WHERE id=120;
UPDATE abilities SET description_en = 'Skills that negate being coated in snow or mud.' WHERE id=121;
UPDATE abilities SET description_en = 'Skills that negate the tremors caused by large monsters.' WHERE id=122;
UPDATE abilities SET description_en = 'Skills that prevent your items from being stolen.' WHERE id=123;
UPDATE abilities SET description_en = 'Skills that affect the likelihood of being targeted by monsters.' WHERE id=124;
UPDATE abilities SET description_en = 'Skills that cause monsters to react as if you are carrying a Torch, even when you aren\'t.' WHERE id=125;
UPDATE abilities SET description_en = 'Skills that make it possible to automatically block attacks when your weapon is drawn. (Blademaster Only)' WHERE id=126;
UPDATE abilities SET description_en = 'Skills that are useful against the Frenzy.' WHERE id=127;
UPDATE abilities SET description_en = 'Skills that make it easier to mount and topple monsters.' WHERE id=128;
UPDATE abilities SET description_en = 'Skills that increase elemental damage (Fire, Water, Thunder, Ice, Dragon) of critical hits.' WHERE id=129;
UPDATE abilities SET description_en = 'Skills that increase abnormal status attack potency (Sleep, Paralysis, Poison, Blast) when landing a critical hit.' WHERE id=130;
UPDATE abilities SET description_en = 'Skills that prolong the time window certain ammo and arrows can hit at maximum power. (Gunner Only)' WHERE id=131;
UPDATE abilities SET description_en = 'Skills that allow consumption of mushrooms and grant certain benefits as a result.' WHERE id=132;
UPDATE abilities SET description_en = 'Skills that give you a chance of reusing items you eat and drink.' WHERE id=133;
UPDATE abilities SET description_en = 'Skills that negate or double the effects of Bleeding on you.' WHERE id=134;
UPDATE abilities SET description_en = 'Skills that negate the movement- hindering effects of the Webbed and Tarred statuses.' WHERE id=135;
UPDATE abilities SET description_en = 'Skills that prevent your attacks from being deflected and halve the rate Sharpness decreases. (Blademaster Only)' WHERE id=136;
UPDATE abilities SET description_en = 'Skills that let you eat meat and items faster, and give you benefits for eating Raw Meat or mushrooms.' WHERE id=137;
UPDATE abilities SET description_en = 'Skills that make you stronger each time you faint, mitigate Stamina depletion except when blocking/evading, and increase potency of Exhaust attacks.' WHERE id=138;
UPDATE abilities SET description_en = 'Skills that unlock latent weapon elements, and power up elemental and abnormal status attacks.' WHERE id=139;
UPDATE abilities SET description_en = 'Skills that increase bomb/Blast damage, increase bomb- and trap- setting speed, and ensure bomb/ trap Combinations never fail.' WHERE id=140;
UPDATE abilities SET description_en = 'Skills that increase the effectiveness of attacks that Exhaust and Stun monsters.' WHERE id=141;
UPDATE abilities SET description_en = 'Skills that increase the efficacy of Health recovery items and sometimes lower damage taken.' WHERE id=142;
UPDATE abilities SET description_en = 'Skills that increase ammo capacity, Combination success rate, and likelihood of not being targeted. (Gunner Only)' WHERE id=143;
