<?php

namespace MH4Editor\MH4EditorBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ItemRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ItemRepository extends EntityRepository
{
    public function getMostBuyedItems()
    {
        $query = $this->getEntityManager()->
            createQuery("SELECT i FROM MH4EditorBundle:Item i WHERE i.timesBought > 0 ORDER BY i.timesBought DESC");

        $result = $query->getResult();

        return $result;

    }

    public function getUsersItemBoughtList()
    {
    	$query = $this->getEntityManager()->
            createQuery("SELECT i FROM MH4EditorBundle:ItemBought i");

        $result = $query->getResult();

        return $result;
    }
}