<?php

namespace MH4Editor\MH4EditorBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ItemRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TalismanRepository extends EntityRepository
{
    public function getGeneratedTalismans()
    {
        $query = $this->getEntityManager()->
            createQuery("SELECT t FROM MH4EditorBundle:TalismanGenerated t");

        $result = $query->getResult();

        return $result;

    }
}