<?php

namespace MH4Editor\MH4EditorBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ItemRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{
    public function getUsersLastAccessList()
    {
        $query = $this->getEntityManager()->
            createQuery("SELECT u FROM MH4EditorBundle:User u");

        $result = $query->getResult();

        return $result;

    }

    public function getItemQuotaByUser($user)
    {
    	$query = $this->getEntityManager()->
            createQuery("SELECT u FROM MH4EditorBundle:User u WHERE u = :user");
        $query->setParameter("user",$user);

        $user = $query->getSingleResult();
        $HR = $user->getHunterHR() !== 0 ? $user->getHunterHR() : 1;

        $perc = array(
        	"dailyQuota" => $user->getItemsQuota(),
        	"totalQuota" => intval(($HR * 5) + User::ITEM_QUOTA_BASE )
        );

        return $perc;
    }

    public function getTalismanQuotaByUser($user)
    {
    	$query = $this->getEntityManager()->
            createQuery("SELECT u FROM MH4EditorBundle:User u WHERE u = :user");
        $query->setParameter("user",$user);

        $user = $query->getSingleResult();
        $HR = $user->getHunterHR() !== 0 ? $user->getHunterHR() : 1;

        $perc = array(
        	"dailyQuota" => $user->getTalismansQuota(),
        	"totalQuota" => intval(($HR * 0.1) + User::TALISMAN_QUOTA_BASE )
        );

        return $perc;
    }

    public function expandItemQuotaByUser($user,$quota)
    {
    	$em = $this->getEntityManager();
    	$user->setItemsQuota($quota);
    	$em->persist($user);
    	$em->flush();
    	return;
    }

    public function expandTalismanQuotaByUser($user,$quota)
    {
    	$em = $this->getEntityManager();
    	$user->setTalismansQuota($quota);
    	$em->persist($user);
    	$em->flush();
    	return;
    }
}