fort42:
    resource: "@Fort42Bundle/Resources/config/routing.yml"
    prefix:   /

mh4_api_connector:
    resource: "@MH4APIConnectorBundle/Resources/config/routing.yml"
    prefix:   /

mh4_api1:
    resource: "@MH4API1Bundle/Resources/config/routing.yml"
    prefix:   /

mh4_cipher:
    resource: "@MH4CipherBundle/Resources/config/routing.yml"
    prefix:   /

mh4_editor:
    resource: "@MH4EditorBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation