# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    app.user_locale_listener:
        class: MH4Editor\MH4EditorBundle\EventListener\UserLocaleListener
        arguments: ["%kernel.default_locale%"]
        tags:
            - { name: kernel.event_subscriber }

    kernel.listener.banned_listener:
        class: MH4Editor\MH4EditorBundle\EventListener\KernelListener
        arguments: [@router,@security.context,@translator,@session]
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest}

    app.user_logout_success_listener:
        class: MH4Editor\MH4EditorBundle\EventListener\LogoutSuccessListener
        arguments: [@security.context,@translator,@session,@service_container]
